export const COLUMN_DIVIDER_WIDTH = 1;
export const COLUMN_HIDDEN_WIDTH = 6;
export const COLUMN_RESIZE_TRANSITION_DURATION = 300;
export const COLUMN_HIDE_DURATION = 500;
export const COLUMN_OPEN_WIDTH = 100 - (COLUMN_HIDDEN_WIDTH + COLUMN_DIVIDER_WIDTH) * 3;
export const COLUMN_CLOSE_WIDTH = (100 - COLUMN_DIVIDER_WIDTH * 3) / 4;
export const COLUMN_INNER_OFFSET = 24

export const TASK_MIN_WIDTH = 200
export const TASK_MAX_WIDTH = 320